### ISSUE TITLE
Supporting livelossplot

### ISSUE THREAD

**Issue by stared** [GRAAL-Research/pytoune#10]
I know it is shameless self-advertisement, but I https://github.com/stared/livelossplot to make it easy to have inline training plots in Jupyter Notebook. 

Right now I support Keras out-of-box. There is an API to add it anywhere, see https://github.com/stared/livelossplot/blob/master/minimal_example.ipynb. I think that it would be nice if it worked with PyToune. Any ideas how to make it plug&play for the end user?

**Comment by freud14** [comment]
I just made a pull request to your project. Let me know what you think.

**Comment by stared** [comment]
@freud14 Great!

**Comment by stared** [comment]
Accepted PR, released on PyPI with `livelossplot 0.2.0`.
